/**
 * Port of cli-tools/sail-model-deploy.js: list models, list deployments, reuse-or-create the
 * `<model>_autogenerated` configuration, create the deployment, read status. Every HTTP call is
 * mocked; the assertions pin the exact AI Core paths, headers and bodies the CLI uses.
 */
import { describe, it, expect, jest, beforeEach } from '@jest/globals';

jest.mock('@libs/logger', () => ({ getDefaultLogger: () => ({ info: jest.fn(), warn: jest.fn(), error: jest.fn(), debug: jest.fn(), trace: jest.fn() }) }));
jest.mock('axios');
jest.mock('../src/services/modelService', () => ({ __esModule: true, getAuthToken: jest.fn(async () => 'tok'), clearModelsCache: jest.fn(), default: { getAuthToken: jest.fn(async () => 'tok'), clearModelsCache: jest.fn() } }));
jest.mock('../src/services/deploymentDiscoveryService', () => ({ __esModule: true, default: { clearCache: jest.fn() }, clearCache: jest.fn() }));
jest.mock('../src/services/configService', () => ({ __esModule: true, default: { getSAPAICoreConfig: () => ({ url: 'https://ai.example', resourceGroup: 'default' }) }, getSAPAICoreConfig: () => ({ url: 'https://ai.example', resourceGroup: 'default' }) }));

import axios from 'axios';
import * as svc from '../src/services/deploymentManagementService';
import { clearModelsCache } from '../src/services/modelService';
import { clearCache } from '../src/services/deploymentDiscoveryService';

const get = axios.get as jest.Mock<any>;
const post = axios.post as jest.Mock<any>;

const MODELS = { resources: [{ model: 'gpt-5.4', displayName: 'GPT-5.4', provider: 'OpenAI', executableId: 'azure-openai', versions: [{ name: '2026-03-05', isLatest: true }] }] };
const dep = (o: any) => ({ id: 'd1', status: 'RUNNING', configurationId: 'c1', configurationName: 'gpt-5.4_autogenerated', createdAt: 't', modifiedAt: 't', deploymentUrl: 'https://dep', details: { resources: { backendDetails: { model: { name: 'gpt-5.4', version: 'latest' } } } }, ...o });

beforeEach(() => { get.mockReset(); post.mockReset(); });

describe('listDeploymentsForModel', () => {
  it('filters deployments by backend model name and maps the CLI fields', async () => {
    get.mockResolvedValueOnce({ data: { resources: [dep({}), dep({ id: 'd2', details: { resources: { backendDetails: { model: { name: 'other' } } } } })] } });
    const r = await svc.listDeploymentsForModel('gpt-5.4');
    expect(get).toHaveBeenCalledWith('https://ai.example/v2/lm/deployments', expect.objectContaining({ headers: expect.objectContaining({ Authorization: 'Bearer tok', 'AI-Resource-Group': 'default' }) }));
    expect(r).toEqual([{ id: 'd1', status: 'RUNNING', configurationId: 'c1', configurationName: 'gpt-5.4_autogenerated', createdAt: 't', modifiedAt: 't', deploymentUrl: 'https://dep', modelVersion: 'latest' }]);
  });
});

describe('createDeployment', () => {
  it('404 when the model is unknown', async () => {
    get.mockResolvedValueOnce({ data: { resources: [] } });
    await expect(svc.createDeployment('nope')).rejects.toMatchObject({ status: 404, code: 'model_not_found' });
  });

  it('409 when a latest/RUNNING deployment exists', async () => {
    get.mockResolvedValueOnce({ data: MODELS }).mockResolvedValueOnce({ data: { resources: [dep({})] } });
    await expect(svc.createDeployment('gpt-5.4')).rejects.toMatchObject({ status: 409, code: 'deployment_exists', details: { deploymentId: 'd1', status: 'RUNNING' } });
  });

  it('reuses an existing configuration, creates the deployment, clears both caches', async () => {
    get.mockResolvedValueOnce({ data: MODELS })
       .mockResolvedValueOnce({ data: { resources: [] } })
       .mockResolvedValueOnce({ data: { resources: [{ id: 'cfg-9', name: 'gpt-5.4_autogenerated', parameterBindings: [{ key: 'modelName', value: 'gpt-5.4' }] }] } });
    post.mockResolvedValueOnce({ data: { id: 'd-new', status: 'PENDING' } });
    const r = await svc.createDeployment('gpt-5.4');
    expect(post).toHaveBeenCalledTimes(1);
    expect(post).toHaveBeenCalledWith('https://ai.example/v2/lm/deployments', { configurationId: 'cfg-9' }, expect.anything());
    expect(r).toEqual({ deploymentId: 'd-new', status: 'PENDING', configurationId: 'cfg-9', reusedConfiguration: true, model: 'gpt-5.4' });
    expect(clearModelsCache).toHaveBeenCalled();
    expect(clearCache).toHaveBeenCalled();
  });

  it('creates the configuration with the CLI body when none exists', async () => {
    get.mockResolvedValueOnce({ data: MODELS }).mockResolvedValueOnce({ data: { resources: [] } }).mockResolvedValueOnce({ data: { resources: [] } });
    post.mockResolvedValueOnce({ data: { id: 'cfg-new', name: 'gpt-5.4_autogenerated' } }).mockResolvedValueOnce({ data: { id: 'd-new', status: 'UNKNOWN' } });
    const r = await svc.createDeployment('gpt-5.4');
    expect(post.mock.calls[0][0]).toBe('https://ai.example/v2/lm/configurations');
    expect(post.mock.calls[0][1]).toEqual({ name: 'gpt-5.4_autogenerated', executableId: 'azure-openai', scenarioId: 'foundation-models', versionId: '0.0.1', parameterBindings: [{ key: 'modelName', value: 'gpt-5.4' }] });
    expect(r.reusedConfiguration).toBe(false);
    expect(r.configurationId).toBe('cfg-new');
  });
});

describe('getDeploymentStatus', () => {
  it('reads /v2/lm/deployments/:id', async () => {
    get.mockResolvedValueOnce({ data: { id: 'd1', status: 'RUNNING', deploymentUrl: 'https://dep', targetStatus: 'RUNNING', lastOperation: 'CREATE' } });
    expect(await svc.getDeploymentStatus('d1')).toEqual({ id: 'd1', status: 'RUNNING', deploymentUrl: 'https://dep', targetStatus: 'RUNNING', lastOperation: 'CREATE' });
    expect(get).toHaveBeenCalledWith('https://ai.example/v2/lm/deployments/d1', expect.anything());
  });
});
