/* Regenerates webapp/model/providerMarks.ts from two icon packages:
   - @lobehub/icons-static-svg (MIT) for the AI providers — the same marks the SAP Model Library
     and other open-source gateways display,
   - simple-icons (CC0-1.0) for SAP.
   Run: pnpm run generate:marks — commit the result. */
import * as fs from 'fs';
import * as path from 'path';

const SOURCES: Record<string, [string, string]> = {
  Anthropic:    ['@lobehub/icons-static-svg', 'anthropic'],
  OpenAI:       ['@lobehub/icons-static-svg', 'openai'],
  Amazon:       ['@lobehub/icons-static-svg', 'aws'],
  Cohere:       ['@lobehub/icons-static-svg', 'cohere'],
  'Mistral AI': ['@lobehub/icons-static-svg', 'mistral'],
  Google:       ['@lobehub/icons-static-svg', 'google'],
  NVIDIA:       ['@lobehub/icons-static-svg', 'nvidia'],
  Perplexity:   ['@lobehub/icons-static-svg', 'perplexity'],
  SAP:          ['simple-icons', 'sap']
};
const FILL = '#32363a'; // sapContent_IconColor of sap_horizon; the marks are monochrome by design

function innerSvg(pkg: string, slug: string): { viewBox: string; body: string } {
  const file = path.join(__dirname, '..', 'node_modules', pkg, 'icons', `${slug}.svg`);
  const svg = fs.readFileSync(file, 'utf8');
  const viewBoxMatch = /viewBox="([^"]+)"/.exec(svg);
  const viewBox = viewBoxMatch ? viewBoxMatch[1] : '0 0 24 24';
  const body = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/<title>[\s\S]*?<\/title>/g, '')
    .replace(/fill="currentColor"/g, `fill="${FILL}"`).replace(/stroke="currentColor"/g, `stroke="${FILL}"`).trim();
  return { viewBox, body };
}

const entries = Object.entries(SOURCES).map(([provider, [pkg, slug]]) => {
  const { viewBox, body } = innerSvg(pkg, slug);
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" fill="${FILL}">${body}</svg>`;
  return `  ${JSON.stringify(provider)}: ${JSON.stringify('data:image/svg+xml;utf8,' + encodeURIComponent(svg))}`;
});

const out = `// GENERATED by scripts/generate-provider-marks.ts — do not edit.
// Sources: @lobehub/icons-static-svg@1.95.0 (MIT) for the AI providers, simple-icons@16.30.0 (CC0-1.0) for SAP.
/** Provider display name (as published on /v1/models owned_by) -> self-contained SVG data URI. */
export const PROVIDER_MARKS: Record<string, string> = {
${entries.join(',\n')}
};

export interface ProviderMark { src?: string; initials?: string; }

/** The provider's mark; an unknown provider renders as Avatar initials. */
export function providerMark(provider: string | null | undefined): ProviderMark {
  const name = (provider || '').trim();
  if (PROVIDER_MARKS[name]) return { src: PROVIDER_MARKS[name] };
  const words = name.split(/\\s+/).filter(Boolean);
  return { initials: (words.length > 1 ? words[0][0] + words[1][0] : name.slice(0, 2) || '?').toUpperCase() };
}
`;
fs.writeFileSync(path.join(__dirname, '..', 'webapp', 'model', 'providerMarks.ts'), out);
console.log(`wrote providerMarks.ts with ${entries.length} marks`);
