/**
 * SAP AI Core deployment management for the admin's Model Library (spec section 5). A port of
 * cli-tools/sail-model-deploy.js — same five calls, same configuration naming, same refusal when a
 * latest/RUNNING deployment already exists. The CLI stays as it is (zero-dependency, used outside
 * the stack). Only the gateway holds AI Core credentials, so this lives here and the admin calls it
 * over /api/admin/deployments with its service key.
 */
import axios from 'axios';
import { getDefaultLogger } from '@libs/logger';
import configService from './configService';
import { getAuthToken, clearModelsCache } from './modelService';
import { clearCache as clearDiscoveryCache } from './deploymentDiscoveryService';

const logger = getDefaultLogger();

export class DeploymentError extends Error {
  status: number; code: string; details?: any;
  constructor(status: number, code: string, message: string, details?: any) { super(message); this.status = status; this.code = code; this.details = details; }
}

export interface DeploymentSummary {
  id: string; status: string; configurationId: string; configurationName: string;
  createdAt: string; modifiedAt: string; deploymentUrl: string | null; modelVersion: string | null;
}

function base(): { url: string; headers: Record<string, string> } {
  const cfg = configService.getSAPAICoreConfig();
  return { url: `${cfg.url}/v2`, headers: { 'AI-Resource-Group': cfg.resourceGroup || 'default', Accept: 'application/json' } };
}

async function authed(): Promise<{ url: string; headers: Record<string, string> }> {
  const b = base();
  const token = await getAuthToken();
  return { url: b.url, headers: { ...b.headers, Authorization: `Bearer ${token}` } };
}

async function listFoundationModels(): Promise<any[]> {
  const { url, headers } = await authed();
  const r = await axios.get(`${url}/lm/scenarios/foundation-models/models`, { headers, timeout: 30000 });
  return r.data?.resources || [];
}

async function listAllDeployments(): Promise<any[]> {
  const { url, headers } = await authed();
  const r = await axios.get(`${url}/lm/deployments`, { headers, timeout: 30000 });
  return r.data?.resources || [];
}

const backendModel = (d: any) => d?.details?.resources?.backendDetails?.model;

export async function listDeploymentsForModel(model: string): Promise<DeploymentSummary[]> {
  const all = await listAllDeployments();
  return all.filter(d => backendModel(d)?.name === model).map(d => ({
    id: d.id, status: d.status || 'UNKNOWN', configurationId: d.configurationId, configurationName: d.configurationName,
    createdAt: d.createdAt, modifiedAt: d.modifiedAt, deploymentUrl: d.deploymentUrl ?? null, modelVersion: backendModel(d)?.version ?? null
  }));
}

export async function createDeployment(model: string): Promise<{ deploymentId: string; status: string; configurationId: string; reusedConfiguration: boolean; model: string }> {
  const models = await listFoundationModels();
  const info = models.find(m => m.model === model);
  if (!info) throw new DeploymentError(404, 'model_not_found', `Model '${model}' not found in SAP AI Core`);

  const deployments = await listAllDeployments();
  const existing = deployments.find(d => backendModel(d)?.name === model && (backendModel(d)?.version === 'latest' || d.status === 'RUNNING'));
  if (existing) throw new DeploymentError(409, 'deployment_exists', `Deployment already exists for '${model}'`, { deploymentId: existing.id, status: existing.status });

  const { url, headers } = await authed();
  const configs = (await axios.get(`${url}/lm/configurations`, { headers, timeout: 30000 })).data?.resources || [];
  let configurationId: string; let reusedConfiguration = false;
  const reusable = configs.find((c: any) => (c.parameterBindings || []).some((p: any) => p.key === 'modelName' && p.value === model));
  if (reusable) {
    configurationId = reusable.id; reusedConfiguration = true;
  } else {
    const body = { name: `${model}_autogenerated`, executableId: info.executableId, scenarioId: 'foundation-models', versionId: '0.0.1', parameterBindings: [{ key: 'modelName', value: model }] };
    const created = await axios.post(`${url}/lm/configurations`, body, { headers: { ...headers, 'Content-Type': 'application/json' }, timeout: 30000 });
    configurationId = created.data.id;
  }

  const dep = await axios.post(`${url}/lm/deployments`, { configurationId }, { headers: { ...headers, 'Content-Type': 'application/json' }, timeout: 30000 });
  clearModelsCache();
  clearDiscoveryCache();
  logger.info('DeploymentManagement', `Deployment ${dep.data.id} created for ${model} (configuration ${configurationId}, reused=${reusedConfiguration})`);
  return { deploymentId: dep.data.id, status: dep.data.status || 'UNKNOWN', configurationId, reusedConfiguration, model };
}

export async function getDeploymentStatus(id: string): Promise<{ id: string; status: string; deploymentUrl: string | null; targetStatus: string | null; lastOperation: string | null }> {
  const { url, headers } = await authed();
  const r = await axios.get(`${url}/lm/deployments/${encodeURIComponent(id)}`, { headers, timeout: 30000 });
  const d = r.data || {};
  return { id: d.id ?? id, status: d.status || 'UNKNOWN', deploymentUrl: d.deploymentUrl ?? null, targetStatus: d.targetStatus ?? null, lastOperation: d.lastOperation ?? null };
}

export default { listDeploymentsForModel, createDeployment, getDeploymentStatus, DeploymentError };
